{
 "title": "Phalanx dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(grpc_method,instance)(rate(phalanx_grpc_server_handled_total{grpc_code=~\"OK\"}[1m]))",
     "legendFormat": "{{ grpc_method }} {{grpc_code }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Error Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance, grpc_method)(rate(phalanx_grpc_server_handled_total{grpc_code=~\"(Unknown|Internal)\"}[1m]))",
     "legendFormat": "{{ grpc_method }} {{grpc_code }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(phalanx_grpc_server_handling_seconds_sum[1m])\n/\nrate(phalanx_grpc_server_handling_seconds_count[1m])",
     "legendFormat": "{{ grpc_method }} {{ instance }}"
    }
   ]
  }
 ]
}