name: Integration

on:
  workflow_dispatch:
    branches: [ main ]
  #schedule:
  #  - cron: 0 0 * * SUN
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    services:
      etcd:
        image: quay.io/coreos/etcd:latest
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
        ports:
          - 2379:2379
      minio:
        image: mosuka/minio:latest
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: miniosecret
        ports:
          - 9000:9000
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: s3,dynamodb,dynamodbstreams
          DEFAULT_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
        ports:
          - 4566:4566

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependcies
        run: go get -v -t -d ./...

      - name: Create .env file
        run: |
          touch .env
          echo "MINIO_ROOT_USER=minio" >> .env
          echo "MINIO_ROOT_PASSWORD=miniosecret" >> .env
          echo "MINIO_VOLUMES=/data" >> .env
          echo "MINIO_OPTS=--console-address :9001" >> .env
          echo "MINIO_REGION_NAME=us-east-1" >> .env
          echo "MINIO_ACCESS_KEY=minio" >> .env
          echo "MINIO_SECRET_KEY=miniosecret" >> .env
          echo "MINIO_ENDPOINT=127.0.0.1:9000" >> .env
          echo "MINIO_SECURE=false" >> .env
          echo "AWS_ACCESS_KEY_ID=dummy" >> .env
          echo "AWS_SECRET_ACCESS_KEY=dummy" >> .env
          echo "AWS_DEFAULT_REGION=ap-northeast-1" >> .env
          echo "AWS_ENDPOINT_URL=http://localhost:4566" >> .env
          echo "AWS_USE_PATH_STYLE=true" >> .env
          echo "ETCD_ENDPOINTS=localhost:2379" >> .env

      - name: Test
        run: go test -v -tags=integration ./...
