name: Run periodic tests on multi environment

on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * SUN

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.1
        ports:
          - 2379:2379

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependcies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v -tags=integration ./...
